spring:
  application:
    name: api-user

eureka:
  client:
    service-url:
      defaultZone: http://api-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:0}