eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: '20000'
  ConnectTimeout: '10000'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: '60000'

zuul:
  routes:
    payroll:
      service-id: api-payroll
      path: /api-payroll/**
    worker:
      path: /api-worker/**
      service-id: api-worker
    user:
      path: /user/**
      service-id: user

server:
  port: 8765

spring:
  application:
    name: api-gateway