eureka:
  client:
    service-url:
      defaultZone: http://api-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

ribbon:
  ReadTimeout: '20000'
  ConnectTimeout: '10000'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: '60000'

spring:
  application:
    name: api-payroll

server:
  port: ${PORT:0}
