eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: '20000'
  ConnectTimeout: '10000'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: '60000'

spring:
  application:
    name: api-payroll

server:
  port: 8085
